package nz.co.blink.debit.helpers;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import nz.co.blink.debit.config.BlinkDebitConfig;
import nz.co.blink.debit.exception.BlinkInvalidValueException;
import nz.co.blink.debit.exception.BlinkServiceException;
import nz.co.blink.debit.service.AccessTokenManager;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.io.IOException;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.List;
import java.util.UUID;
import java.util.stream.Collectors;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class HttpClientHelperTest {

    private static final String BASE_URL = "https://test.blinkpay.co.nz";
    private static final String ACCESS_TOKEN = "test-access-token";
    private static final String REQUEST_ID = "test-request-id";
    private static final String CALLER_KEY = "caller-supplied-not-a-uuid";

    @Mock
    private HttpClient httpClient;

    @Mock
    private AccessTokenManager tokenManager;

    @Mock
    private HttpResponse<String> httpResponse;

    private BlinkDebitConfig config;
    private ObjectMapper objectMapper;
    private HttpClientHelper httpHelper;

    @BeforeEach
    void setUp() throws BlinkInvalidValueException {
        config = BlinkDebitConfig.builder()
                .debitUrl(BASE_URL)
                .clientId("test-client")
                .clientSecret("test-secret")
                .timeout(Duration.ofSeconds(30))
                .build();

        objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());

        httpHelper = new HttpClientHelper(httpClient, config, objectMapper, tokenManager);

        // Default mock behavior
        when(tokenManager.getAccessToken()).thenReturn(ACCESS_TOKEN);
    }

    // ===== POST Request Tests =====

    @Test
    void testPostSuccess() throws Exception {
        TestRequest requestBody = new TestRequest("test-data");
        TestResponse expectedResponse = new TestResponse("response-data");

        when(httpResponse.statusCode()).thenReturn(200);
        when(httpResponse.body()).thenReturn(objectMapper.writeValueAsString(expectedResponse));
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        TestResponse result = httpHelper.post("/test-path", requestBody, TestResponse.class, REQUEST_ID);

        assertThat(result).isNotNull();
        assertThat(result.data).isEqualTo("response-data");

        // Verify headers were set correctly
        ArgumentCaptor<HttpRequest> requestCaptor = ArgumentCaptor.forClass(HttpRequest.class);
        verify(httpClient).send(requestCaptor.capture(), any(HttpResponse.BodyHandler.class));

        HttpRequest capturedRequest = requestCaptor.getValue();
        assertThat(capturedRequest.uri().toString()).isEqualTo(BASE_URL + "/test-path");
        assertThat(capturedRequest.headers().firstValue("Content-Type")).hasValue("application/json");
        assertThat(capturedRequest.headers().firstValue("Accept")).hasValue("application/json");
        assertThat(capturedRequest.headers().firstValue("Authorization")).hasValue("Bearer " + ACCESS_TOKEN);
        assertThat(capturedRequest.headers().firstValue("request-id")).hasValue(REQUEST_ID);
        assertThat(capturedRequest.timeout()).hasValue(Duration.ofSeconds(30));
    }

    @Test
    void testPostWithAutoGeneratedRequestId() throws Exception {
        TestRequest requestBody = new TestRequest("test-data");
        TestResponse expectedResponse = new TestResponse("response-data");

        when(httpResponse.statusCode()).thenReturn(201);
        when(httpResponse.body()).thenReturn(objectMapper.writeValueAsString(expectedResponse));
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        TestResponse result = httpHelper.post("/test-path", requestBody, TestResponse.class);

        assertThat(result).isNotNull();

        // Verify request-id header was set (should be a UUID)
        ArgumentCaptor<HttpRequest> requestCaptor = ArgumentCaptor.forClass(HttpRequest.class);
        verify(httpClient).send(requestCaptor.capture(), any(HttpResponse.BodyHandler.class));
        assertThat(requestCaptor.getValue().headers().firstValue("request-id")).isPresent();
    }

    @Test
    void testPost4xxError() throws Exception {
        TestRequest requestBody = new TestRequest("test-data");
        String errorBody = "{\"error\":\"Bad Request\"}";

        when(httpResponse.statusCode()).thenReturn(400);
        when(httpResponse.body()).thenReturn(errorBody);
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        assertThatThrownBy(() -> httpHelper.post("/test-path", requestBody, TestResponse.class, REQUEST_ID))
                .isInstanceOf(BlinkServiceException.class)
                .hasMessageContaining("Request failed: HTTP 400")
                .hasMessageContaining(errorBody);
    }

    @Test
    void testPost5xxError() throws Exception {
        TestRequest requestBody = new TestRequest("test-data");
        String errorBody = "{\"error\":\"Internal Server Error\"}";

        when(httpResponse.statusCode()).thenReturn(500);
        when(httpResponse.body()).thenReturn(errorBody);
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        assertThatThrownBy(() -> httpHelper.post("/test-path", requestBody, TestResponse.class, REQUEST_ID))
                .isInstanceOf(BlinkServiceException.class)
                .hasMessageContaining("Request failed: HTTP 500")
                .hasMessageContaining(errorBody);
    }

    @Test
    void testPostJsonSerializationError() throws JsonProcessingException {
        ObjectMapper failingMapper = mock(ObjectMapper.class);
        when(failingMapper.writeValueAsString(any())).thenThrow(new JsonProcessingException("Serialization error") {});

        HttpClientHelper helperWithFailingMapper = new HttpClientHelper(
                httpClient, config, failingMapper, tokenManager);

        assertThatThrownBy(() -> helperWithFailingMapper.post("/test", new TestRequest("data"), TestResponse.class))
                .isInstanceOf(BlinkServiceException.class)
                .hasMessageContaining("Failed to serialize request body");
    }

    @Test
    void testPostIOException() throws Exception {
        TestRequest requestBody = new TestRequest("test-data");

        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenThrow(new IOException("Network error"));

        assertThatThrownBy(() -> httpHelper.post("/test-path", requestBody, TestResponse.class, REQUEST_ID))
                .isInstanceOf(BlinkServiceException.class)
                .hasMessageContaining("Network error after 3 attempts");
    }

    @Test
    void testPostInterruptedException() throws Exception {
        TestRequest requestBody = new TestRequest("test-data");

        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenThrow(new InterruptedException("Thread interrupted"));

        assertThatThrownBy(() -> httpHelper.post("/test-path", requestBody, TestResponse.class, REQUEST_ID))
                .isInstanceOf(BlinkServiceException.class)
                .hasMessageContaining("Interrupted during POST request");

        // Verify interrupt flag is set
        assertThat(Thread.currentThread().isInterrupted()).isTrue();
        Thread.interrupted(); // Clear interrupt flag for other tests
    }

    // ===== GET Request Tests =====

    @Test
    void testGetSuccess() throws Exception {
        TestResponse expectedResponse = new TestResponse("get-response");

        when(httpResponse.statusCode()).thenReturn(200);
        when(httpResponse.body()).thenReturn(objectMapper.writeValueAsString(expectedResponse));
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        TestResponse result = httpHelper.get("/test-path", TestResponse.class, REQUEST_ID);

        assertThat(result).isNotNull();
        assertThat(result.data).isEqualTo("get-response");

        // Verify headers
        ArgumentCaptor<HttpRequest> requestCaptor = ArgumentCaptor.forClass(HttpRequest.class);
        verify(httpClient).send(requestCaptor.capture(), any(HttpResponse.BodyHandler.class));

        HttpRequest capturedRequest = requestCaptor.getValue();
        assertThat(capturedRequest.uri().toString()).isEqualTo(BASE_URL + "/test-path");
        assertThat(capturedRequest.headers().firstValue("Accept")).hasValue("application/json");
        assertThat(capturedRequest.headers().firstValue("Authorization")).hasValue("Bearer " + ACCESS_TOKEN);
        assertThat(capturedRequest.headers().firstValue("request-id")).hasValue(REQUEST_ID);
        assertThat(capturedRequest.method()).isEqualTo("GET");
    }

    @Test
    void testGetWithEmptyResponse() throws Exception {
        when(httpResponse.statusCode()).thenReturn(200);
        when(httpResponse.body()).thenReturn("");
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        TestResponse result = httpHelper.get("/test-path", TestResponse.class, REQUEST_ID);

        assertThat(result).isNull();
    }

    @Test
    void testGet404Error() throws Exception {
        when(httpResponse.statusCode()).thenReturn(404);
        when(httpResponse.body()).thenReturn("{\"error\":\"Not Found\"}");
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        assertThatThrownBy(() -> httpHelper.get("/test-path", TestResponse.class, REQUEST_ID))
                .isInstanceOf(BlinkServiceException.class)
                .hasMessageContaining("Request failed: HTTP 404");
    }

    @Test
    void testGetIOException() throws Exception {
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenThrow(new IOException("Connection timeout"));

        assertThatThrownBy(() -> httpHelper.get("/test-path", TestResponse.class, REQUEST_ID))
                .isInstanceOf(BlinkServiceException.class)
                .hasMessageContaining("Network error after 3 attempts");
    }

    // ===== DELETE Request Tests =====

    @Test
    void testDeleteSuccess() throws Exception {
        when(httpResponse.statusCode()).thenReturn(204);
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        httpHelper.delete("/test-path", REQUEST_ID);

        ArgumentCaptor<HttpRequest> requestCaptor = ArgumentCaptor.forClass(HttpRequest.class);
        verify(httpClient).send(requestCaptor.capture(), any(HttpResponse.BodyHandler.class));

        HttpRequest capturedRequest = requestCaptor.getValue();
        assertThat(capturedRequest.uri().toString()).isEqualTo(BASE_URL + "/test-path");
        assertThat(capturedRequest.headers().firstValue("Authorization")).hasValue("Bearer " + ACCESS_TOKEN);
        assertThat(capturedRequest.headers().firstValue("request-id")).hasValue(REQUEST_ID);
        assertThat(capturedRequest.method()).isEqualTo("DELETE");
    }

    @Test
    void testDeleteWithAutoGeneratedRequestId() throws Exception {
        when(httpResponse.statusCode()).thenReturn(204);
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        httpHelper.delete("/test-path");

        ArgumentCaptor<HttpRequest> requestCaptor = ArgumentCaptor.forClass(HttpRequest.class);
        verify(httpClient).send(requestCaptor.capture(), any(HttpResponse.BodyHandler.class));
        assertThat(requestCaptor.getValue().headers().firstValue("request-id")).isPresent();
    }

    @Test
    void testDelete404Error() throws Exception {
        when(httpResponse.statusCode()).thenReturn(404);
        when(httpResponse.body()).thenReturn("{\"error\":\"Not Found\"}");
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        assertThatThrownBy(() -> httpHelper.delete("/test-path", REQUEST_ID))
                .isInstanceOf(BlinkServiceException.class)
                .hasMessageContaining("DELETE request failed: HTTP 404");
    }

    // ===== GET List Request Tests =====

    @Test
    void testGetListSuccess() throws Exception {
        List<TestResponse> expectedList = List.of(
                new TestResponse("item1"),
                new TestResponse("item2"),
                new TestResponse("item3")
        );

        when(httpResponse.statusCode()).thenReturn(200);
        when(httpResponse.body()).thenReturn(objectMapper.writeValueAsString(expectedList));
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        List<TestResponse> result = httpHelper.getList("/test-list", TestResponse.class, REQUEST_ID);

        assertThat(result).hasSize(3);
        assertThat(result.get(0).data).isEqualTo("item1");
        assertThat(result.get(1).data).isEqualTo("item2");
        assertThat(result.get(2).data).isEqualTo("item3");
    }

    @Test
    void testGetListWithEmptyResponse() throws Exception {
        when(httpResponse.statusCode()).thenReturn(200);
        when(httpResponse.body()).thenReturn("");
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        List<TestResponse> result = httpHelper.getList("/test-list", TestResponse.class, REQUEST_ID);

        assertThat(result).isEmpty();
    }

    @Test
    void testGetListWithEmptyJsonArray() throws Exception {
        when(httpResponse.statusCode()).thenReturn(200);
        when(httpResponse.body()).thenReturn("[]");
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        List<TestResponse> result = httpHelper.getList("/test-list", TestResponse.class, REQUEST_ID);

        assertThat(result).isEmpty();
    }

    @Test
    void testGetListDeserializationError() throws Exception {
        when(httpResponse.statusCode()).thenReturn(200);
        when(httpResponse.body()).thenReturn("invalid-json");
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        assertThatThrownBy(() -> httpHelper.getList("/test-list", TestResponse.class, REQUEST_ID))
                .isInstanceOf(BlinkServiceException.class)
                .hasMessageContaining("Failed to deserialize response body");
    }

    // ===== Idempotency Key Tests =====

    @Test
    void testPostSendsCallerSuppliedIdempotencyKeyUnchanged() throws Exception {
        when(httpResponse.statusCode()).thenReturn(201);
        when(httpResponse.body()).thenReturn(objectMapper.writeValueAsString(new TestResponse("ok")));
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        httpHelper.post("/test-path", new TestRequest("test-data"), TestResponse.class, REQUEST_ID, CALLER_KEY);

        ArgumentCaptor<HttpRequest> requestCaptor = ArgumentCaptor.forClass(HttpRequest.class);
        verify(httpClient).send(requestCaptor.capture(), any(HttpResponse.BodyHandler.class));
        assertThat(requestCaptor.getValue().headers().firstValue("idempotency-key")).hasValue(CALLER_KEY);
    }

    @Test
    void testPostReusesCallerSuppliedIdempotencyKeyAcrossRetries() throws Exception {
        HttpResponse<String> serverError = mock(HttpResponse.class);
        when(serverError.statusCode()).thenReturn(503);
        when(httpResponse.statusCode()).thenReturn(201);
        when(httpResponse.body()).thenReturn(objectMapper.writeValueAsString(new TestResponse("ok")));
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(serverError, serverError, httpResponse);

        httpHelper.post("/test-path", new TestRequest("test-data"), TestResponse.class, REQUEST_ID, CALLER_KEY);

        ArgumentCaptor<HttpRequest> requestCaptor = ArgumentCaptor.forClass(HttpRequest.class);
        verify(httpClient, times(3)).send(requestCaptor.capture(), any(HttpResponse.BodyHandler.class));
        assertThat(requestCaptor.getAllValues())
                .hasSize(3)
                .allSatisfy(request ->
                        assertThat(request.headers().firstValue("idempotency-key")).hasValue(CALLER_KEY));
    }

    @Test
    void testPostReusesCallerSuppliedIdempotencyKeyAcrossTokenRefresh() throws Exception {
        HttpResponse<String> unauthorised = mock(HttpResponse.class);
        when(unauthorised.statusCode()).thenReturn(401);
        when(httpResponse.statusCode()).thenReturn(201);
        when(httpResponse.body()).thenReturn(objectMapper.writeValueAsString(new TestResponse("ok")));
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(unauthorised, httpResponse);

        httpHelper.post("/test-path", new TestRequest("test-data"), TestResponse.class, REQUEST_ID, CALLER_KEY);

        verify(tokenManager).refreshToken();
        ArgumentCaptor<HttpRequest> requestCaptor = ArgumentCaptor.forClass(HttpRequest.class);
        verify(httpClient, times(2)).send(requestCaptor.capture(), any(HttpResponse.BodyHandler.class));
        assertThat(requestCaptor.getAllValues())
                .hasSize(2)
                .allSatisfy(request ->
                        assertThat(request.headers().firstValue("idempotency-key")).hasValue(CALLER_KEY));
    }

    @Test
    void testPostGeneratesADistinctIdempotencyKeyPerCallWhenNoneSupplied() throws Exception {
        when(httpResponse.statusCode()).thenReturn(201);
        when(httpResponse.body()).thenReturn(objectMapper.writeValueAsString(new TestResponse("ok")));
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        httpHelper.post("/test-path", new TestRequest("test-data"), TestResponse.class, REQUEST_ID);
        httpHelper.post("/test-path", new TestRequest("test-data"), TestResponse.class, REQUEST_ID);

        ArgumentCaptor<HttpRequest> requestCaptor = ArgumentCaptor.forClass(HttpRequest.class);
        verify(httpClient, times(2)).send(requestCaptor.capture(), any(HttpResponse.BodyHandler.class));
        List<String> keys = requestCaptor.getAllValues().stream()
                .map(request -> request.headers().firstValue("idempotency-key").orElseThrow())
                .collect(Collectors.toList());
        assertThat(keys).doesNotHaveDuplicates();
        keys.forEach(key -> assertThatCode(() -> UUID.fromString(key)).doesNotThrowAnyException());
    }

    @Test
    void testPostGeneratesAUuidWhenTheSuppliedIdempotencyKeyIsNull() throws Exception {
        assertGeneratedUuidIsSentFor(null);
    }

    @Test
    void testPostGeneratesAUuidWhenTheSuppliedIdempotencyKeyIsBlank() throws Exception {
        assertGeneratedUuidIsSentFor("   ");
    }

    private void assertGeneratedUuidIsSentFor(String idempotencyKey) throws Exception {
        when(httpResponse.statusCode()).thenReturn(201);
        when(httpResponse.body()).thenReturn(objectMapper.writeValueAsString(new TestResponse("ok")));
        when(httpClient.send(any(HttpRequest.class), any(HttpResponse.BodyHandler.class)))
                .thenReturn(httpResponse);

        httpHelper.post("/test-path", new TestRequest("test-data"), TestResponse.class, REQUEST_ID, idempotencyKey);

        ArgumentCaptor<HttpRequest> requestCaptor = ArgumentCaptor.forClass(HttpRequest.class);
        verify(httpClient).send(requestCaptor.capture(), any(HttpResponse.BodyHandler.class));
        String sent = requestCaptor.getValue().headers().firstValue("idempotency-key").orElseThrow();
        assertThatCode(() -> UUID.fromString(sent)).doesNotThrowAnyException();
    }

    // ===== Helper Classes =====

    private static class TestRequest {
        public String data;

        public TestRequest() {}

        public TestRequest(String data) {
            this.data = data;
        }
    }

    private static class TestResponse {
        public String data;

        public TestResponse() {}

        public TestResponse(String data) {
            this.data = data;
        }
    }
}
